config/routes.rb
Rails.application.routes.draw do
  match '/auth/:provider/callback' => 'authentications#create', via: [:get, :post]
  root 'home#home'
 
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }
 	mount ActionCable.server => '/cable'

  resources :conversations, only: [:create] do
    member do
      post  :close
    end
    resources :messages, only: [:create]
  end

  resources :home, only: [:index] do
  	collection do
  		get   :home
  	end
    member do
      get   :user_edit
      put   :user_edit
      get   :user_avatar
      post  :user_avatar      
    end
  end
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :sender, foreign_key: :sender_id, class_name: User
  belongs_to :recipient, foreign_key: :recipient_id, class_name: User

  validates :sender_id, uniqueness: { scope: :recipient_id }

  scope :between, -> (sender_id, recipient_id) do
    where(sender_id: sender_id, recipient_id: recipient_id).or(
      where(sender_id: recipient_id, recipient_id: sender_id)
    )
  end

  def self.get(sender_id, recipient_id)
    conversation = between(sender_id, recipient_id).first
    return conversation if conversation.present?

    create(sender_id: sender_id, recipient_id: recipient_id)
  end

  def opposed_user(user)
    user == recipient ? sender : recipient
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def create
    @conversation = Conversation.get(current_user.id, params[:user_id])
    
    add_to_conversations unless conversated?
    respond_to do |format|
      format.js
    end
  end

  def close
    @conversation = Conversation.find(params[:id])
 
    session[:conversations].delete(@conversation.id)
 
    respond_to do |format|
      format.js
    end
  end

  private

  def add_to_conversations
    session[:conversations] ||= []
    session[:conversations] << @conversation.id
  end

  def conversated?
    session[:conversations].include?(@conversation.id)
  end
end

app/views/conversations/_conversation.haml
%li
  .panel.panel-default{"data-conversation-id" => "#{conversation.id}"}
    .panel-heading
      = link_to conversation.opposed_user(user).email, '', class: 'toggle-window'
      = link_to "x", close_conversation_path(conversation), class: "btn btn-default btn-xs pull-right", remote: true, method: :post
    .panel-body{:style => "display: none;"}
      .messages-list
        %ul
          = render 'conversations/conversation_content', messages: conversation.messages, user: user
      %form.new_message
        %input{:name => "conversation_id", :type => "hidden", :value => "#{conversation.id}"}/
        %input{:name => "user_id", :type => "hidden", :value => "#{user.id}"}/
        %textarea.form-control{:name => "body"}
        %input.btn.btn-success{:type => "submit", :value => "Send"}/

app/views/conversations/_conversation_content.html.haml
- messages.each do |message|
  = render message, user: user

app/views/conversations/close.js.haml
$('#conversations-list').find("[data-conversation-id='" + "#{@conversation.id}" + "']").parent().remove();

app/views/conversations/create.js.haml
var conversations = $('#conversations-list');
var conversation = conversations.find("[data-conversation-id='" + "#{@conversation.id}" + "']");

if (conversation.length !== 1) {
conversations.append("#{j(render 'conversations/conversation', conversation: @conversation, user: current_user)}");
conversation = conversations.find("[data-conversation-id='" + "#{@conversation.id}" + "']");
}

conversation.find('.panel-body').show();

var messages_list = conversation.find('.messages-list');
var height = messages_list[0].scrollHeight;
messages_list.scrollTop(height);