config/routes.rb
Rails.application.routes.draw do
  match '/auth/:provider/callback' => 'authentications#create', via: [:get, :post]
  root 'home#home'
 
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }
 	mount ActionCable.server => '/cable'

  resources :conversations, only: [:create] do
    member do
      post  :close
    end
    resources :messages, only: [:create]
  end

  resources :home, only: [:index] do
  	collection do
  		get   :home
  	end
    member do
      get   :user_edit
      put   :user_edit
      get   :user_avatar
      post  :user_avatar      
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	skip_before_filter :verify_authenticity_token, only: [:user_avatar]
  def index
  	session[:conversations] ||= []
 
    @users = User.all.where.not(id: current_user)
    @conversations = Conversation.includes(:recipient, :messages)
                                 .find(session[:conversations])
  end

  def home
  	@user_profile = current_user.profile
  end

  def user_edit
    @profile = current_user.profile
    if request.put?
      debugger
      current_user.update(user_nested_params)
      flash[:notice] = "Updated Successfully!!!"
      redirect_to root_path
    end
  end

  def user_avatar
  	# current_user.profile.remove_picture!
    begin
      pic = params.require(:user_profile).require(:picture)
      current_user.profile.update(picture: pic)
      render json: {status: true, image: current_user.profile.picture.url}
    rescue ActionController::ParameterMissing => e
      render json: {status: false, message: e.message}
    end
  end

  private
  def user_nested_params
    params.require(:user).permit(:email, :user_profile_attributes=>[:id, :first_name, :last_name, :picture, :cover, :_destroy])
  end
end

app/helpers/home_helper.rb
module HomeHelper
	class << self
		
		def time_ago_in_words(from_time, options = {})
	    distance_of_time_in_words(from_time, Time.now, options)
	  end

		def distance_of_time_in_words(from_time, to_time = 0, options = {})
      options = {
        scope: :'datetime.distance_in_words'
      }.merge!(options)

      from_time = from_time.to_time if from_time.respond_to?(:to_time)
      to_time = to_time.to_time if to_time.respond_to?(:to_time)
      from_time, to_time = to_time, from_time if from_time > to_time
      distance_in_minutes = ((to_time - from_time)/60.0).round
      distance_in_seconds = (to_time - from_time).round

      I18n.with_options :locale => options[:locale], :scope => options[:scope] do |locale|
        case distance_in_minutes
          when 0..1
            return distance_in_minutes == 0 ?
                   locale.t(:less_than_x_minutes, :count => 1) :
                   locale.t(:x_minutes, :count => distance_in_minutes) unless options[:include_seconds]

            case distance_in_seconds
              when 0..4   then locale.t :less_than_x_seconds, :count => 5
              when 5..9   then locale.t :less_than_x_seconds, :count => 10
              when 10..19 then locale.t :less_than_x_seconds, :count => 20
              when 20..39 then locale.t :half_a_minute
              when 40..59 then locale.t :less_than_x_minutes, :count => 1
              else             locale.t :x_minutes,           :count => 1
            end

          when 2...45           then locale.t :x_minutes,      :count => distance_in_minutes
          when 45...90          then locale.t :about_x_hours,  :count => 1
          # 90 mins up to 24 hours
          when 90...1440        then locale.t :about_x_hours,  :count => (distance_in_minutes.to_f / 60.0).round
          # 24 hours up to 42 hours
          when 1440...2520      then locale.t :x_days,         :count => 1
          # 42 hours up to 30 days
          when 2520...43200     then locale.t :x_days,         :count => (distance_in_minutes.to_f / 1440.0).round
          # 30 days up to 60 days
          when 43200...86400    then locale.t :about_x_months, :count => (distance_in_minutes.to_f / 43200.0).round
          # 60 days up to 365 days
          when 86400...525600   then locale.t :x_months,       :count => (distance_in_minutes.to_f / 43200.0).round
          else
            if from_time.acts_like?(:time) && to_time.acts_like?(:time)
              fyear = from_time.year
              fyear += 1 if from_time.month >= 3
              tyear = to_time.year
              tyear -= 1 if to_time.month < 3
              leap_years = (fyear > tyear) ? 0 : (fyear..tyear).count{|x| Date.leap?(x)}
              minute_offset_for_leap_year = leap_years * 1440
              # Discount the leap year days when calculating year distance.
              # e.g. if there are 20 leap year days between 2 dates having the same day
              # and month then the based on 365 days calculation
              # the distance in years will come out to over 80 years when in written
              # English it would read better as about 80 years.
              minutes_with_offset = distance_in_minutes - minute_offset_for_leap_year
            else
              minutes_with_offset = distance_in_minutes
            end
            remainder                   = (minutes_with_offset % MINUTES_IN_YEAR)
            distance_in_years           = (minutes_with_offset.div MINUTES_IN_YEAR)
            if remainder < MINUTES_IN_QUARTER_YEAR
              locale.t(:about_x_years,  :count => distance_in_years)
            elsif remainder < MINUTES_IN_THREE_QUARTERS_YEAR
              locale.t(:over_x_years,   :count => distance_in_years)
            else
              locale.t(:almost_x_years, :count => distance_in_years + 1)
            end
        end
      end
    end

  end
end

app/views/home/_pic_cover_modal.html.haml
%button.btn.btn-info.btn-lg.pic_avatar_model{"data-toggle" => "modal", "data-target" => "#picAvatarModal", :style => "display:none;"} Open Modal
#picAvatarModal.modal.fade{:role => "dialog"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal"} &times;
        %h4.modal-title Upload Picture
      .modal-body
        = form_for @user_profile, url: user_avatar_home_path(current_user), method: :post, multipart: true, remote: true do |f|
          = f.file_field :picture
      .modal-footer
        %button.btn.btn-default#save_avatar Save
:javascript
  $("#save_avatar").click(() => {
    $("form.edit_user_profile").ajaxForm({
        url : "#{user_avatar_home_path(current_user)}",
        type: "POST",
        dataType : 'json',
        success : function (response) {
          $('.card.hovercard .avatar > img').attr('src', response.image)
          $("#picAvatarModal").modal("hide");
        }
    }).submit()
  })

app/views/home/_profile_card.html.haml
.container.col-md-12{:style => "padding:0;"}
  .row{:style => "margin:0;"}
    .col-md-12{:style => "padding:0;"}
      .card.hovercard{:style => "margin:0;"}
        -debugger
        .cardheader{:style => "background: url(#{current_user.profile.cover.url || "http://www.f-covers.com/cover/grey-floral-facebook-cover-timeline-banner-for-fb.jpg"}); background-size: cover; height: 135px;"}
        .avatar
          %img{:alt => "", :src => (current_user.profile.picture.url || "http://cdn1.iconfinder.com/data/icons/circle-outlines-colored/512/Robot_User_Profile_Dummy_Avatar_Person_AI-512.png")}/
        .bottom
          .row
            %a.btn.btn-card.btn-info.btn-twitter.btn-sm{:href => "https://twitter.com/webmaniac"}
              %i.fa.fa-twitter
            %a.btn.btn-card.btn-danger.btn-sm{:href => "https://plus.google.com/+ahmshahnuralam", :rel => "publisher"}
              %i.fa.fa-google-plus
          .row
            %a.btn.btn-card.btn-primary.btn-sm{:href => "https://plus.google.com/shahnuralam", :rel => "publisher"}
              %i.fa.fa-facebook
            %a.btn.btn-card.btn-primary.btn-sm{:href => "https://plus.google.com/shahnuralam", :rel => "publisher"}
              %i.fa.fa-linkedin
        .info
          .title
            %a{:href => "http://scripteden.com/", :target => "_blank"}
            = current_user.full_name rescue "New User"
          .desc Passionate designer
          .desc Curious developer
          .desc Tech geek
=render "pic_cover_modal"
:javascript

app/views/home/home.html.haml
%div.main-container.col-md-12.inside-body{:style => "padding:0;"}
  .left-panel.col-md-3.well{:style => "background:skyblue;height:46.6em;padding:0;"}
    = render partial: "profile_card"
  .left-panel.col-md-7.well{:style => "background:red;"}
    hello
  .left-panel.col-md-2.well{:style => "background:green;"}
    hello

app/views/home/index.html.haml
%h2= link_to "Logout", destroy_user_session_path, method: :delete
.col-md-12.col-sm-12
  %ul#conversations-list
    - @conversations.each do |conversation|
      = render 'conversations/conversation', conversation: conversation, user: current_user
%div{:style => "clear:both"}
.col-md-12.col-sm-12
  .panel.panel-primary
    .panel-heading
      %h3.panel-title User list
    .panel-body
      %ul
        - @users.each do |user|
          %li= link_to user.email, conversations_path(user_id: user), remote: true, method: :post

app/views/home/user_edit.html.haml
.well.col-md-6.col-md-offset-3{:style => "margin-top:2%;border-color:black;"}
  = nested_form_for current_user, url: user_edit_home_path(current_user), method: :put, multipart: true do |f|
    = f.fields_for :user_profile do |ff|
      .col-md-6
        .field.well{:style => "border-color:black;"}
          = f.label :email
          %br/
          = f.email_field :email, autofocus: true, class: "form-control"
        .field.well{:style => "border-color:black;"}
          = ff.label :first_name
          %br/
          = ff.text_field :first_name, autocomplete: "off", class: "form-control"
        .field.well{:style => "border-color:black;"}
          = ff.label :last_name
          %br/
          = ff.text_field :last_name, autocomplete: "off", class: "form-control"
      .col-md-6
        .field.well{:style => "border-color:black;"}
          = ff.label :picture
          %br/
          = ff.file_field :picture, class: "form-control"
        .field.well{:style => "border-color:black;"}
          = ff.label :cover
          %br/
          = ff.file_field :cover, class: "form-control"
          = ff.hidden_field :id
    .actions
      = f.submit "Update", class: "form-control btn btn-warning"